<?php
/* @var \Codilar\HelloWorld\Block\HelloWorld $block */
use Magento\Catalog\Model\Product\Visibility;
?>

<div class="form656">
    <form action="<?= $block->getUrl("hello/index/productPost") ?>" method="post" enctype="multipart/form-data">
        <div class="field enabled">
            <label class="label" for="enabled"><span><?php echo __('enable this product?') ?></span></label>
            <div class="control">
                <select name="enabled">
                    <option value="0">No</option>
                    <option value="1">Yes</option>
                </select>
            </div>
        </div>
        <select name="attribute">
            <option value="0">default</option>
        </select>
        <label> Product Name</label><br/> <input name="pname" type="text"/><br/>
        <label>SKU</label><br/> <input name="sku" type="text"/><br/>
        <label>price</</label><br/><input name="price" type="text"/><br/>
        <div class="field stock">
            <label class="label" for="stock"><span><?php echo __('stock status?') ?></span></label>
            <div class="control">
                <select name="stock">
                    <option value="1">in stock</option>
                    <option value="0">out of stock</option>
                </select>
            </div>
        </div>
       <select name="visibility">
            <?php foreach ($block->getVisibilities() as $visibility): ?>
                <option value="<?= $visibility['value'] ?>"><?= $visibility['label'] ?></option>
           <?php endforeach; ?>
       </select>
        <p>categories</</p><br/>
        <select name="category">
            <?php foreach ($block->getAllCategories() as $category): ?>
                <?php /* @var \Magento\Catalog\Model\Category $category */ ?>
                <option value="<?= $category->getId() ?>"><?= $category->getName() ?></option>
            <?php endforeach; ?>
        </select><br/>
        <label>image</label> <br/><input type="file" name="image" accept="image/*"/><br/>
        <br/>
        <input type="submit" name="submit" value="save product"/>

    </form>

</div>